### ISSUE TITLE
Error when adding points to User

### ISSUE THREAD

**Issue by fgiannar** [Trexology/laravel-pointable#1]
After initial setup, when using the example to add points to a user an ErrorException occurs in Transaction.php, line 60

**Object of class Illuminate\Support\Collection could not be converted to int**

I believe `getCurrentPoints` function should return `$currentPoint[0]` _(if found)_.

**Comment by Trexology** [comment]
Thats weird, getCurrentPoints should have a return type of double. which laravel version are you using? I do not have any error on my implementation

**Comment by fgiannar** [comment]
5.2
The query in getCurrentPoints returns a Collection object.

**Comment by Trexology** [comment]
Fixed, issue due to laravel 5.2 replacing pluck() function to value() function
